name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test with NestJS ${{ matrix.nest-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nest-version: ['10.x.x', '11.x.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Install NestJS version
        working-directory: ./packages/core
        run: |
          pnpm add -D @nestjs/common@${{ matrix.nest-version }} @nestjs/core@${{ matrix.nest-version }} @nestjs/testing@${{ matrix.nest-version }}
      - name: Test
        run: pnpm run test:e2e
