name: Test

on:
  workflow_call:

jobs:
  test:
    name: Test with NestJS ${{ matrix.nest-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nest-version: ['10.x.x', '11.x.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: pnpm
      - name: Install NestJS version
        run: |
          pnpm remove @nestjs/common @nestjs/core @nestjs/testing
          pnpm add -D @nestjs/common@${{ matrix.nest-version }} @nestjs/core@${{ matrix.nest-version }} @nestjs/testing@${{ matrix.nest-version }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash
      - name: Test
        run: pnpm run test:e2e
